### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by wanglongtao666** [Yos-X/YBVD_Release#1]
【「𝟒𝑲修复」茗记系列1-4合集 | L-Key工作室作品-哔哩哔哩】 https://b23.tv/pDSDCe6
Application Config: 
- Build Version: 1.0.0-beta03 
- Build Code: 1 
- Current Date: 2023-03-21 15:42:29 

Device Config: 
- Model: M2006J10C 
- Manufacturer: Xiaomi 
- SDK: 31 
- ABIs: arm64-v8a, armeabi-v7a, armeabi 
- Rooted: false 
- Tablet: false 
- Emulator: false 

Stack Trace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.ContentProviderClient.call(java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
	at android.app.DownloadManager$Request.setDestinationInExternalPublicDir(DownloadManager.java:891)
	at q9.i$e$a.p(Unknown Source:331)
	at t7.a.A(Unknown Source:11)
	at k8.a1.run(Unknown Source:88)
	at kotlinx.coroutines.internal.l.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.w(Unknown Source:0)
	at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
	at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
	Suppressed: k8.y0: [p2{Cancelling}@aa87702, Dispatchers.IO]

**Comment by Yos-X** [comment]
好的，将尝试进行问题复现并修复。
